- BUILD.md
I found a few typos and formatting issues with the BUILD.md documentation file:
- Fixed cases where `bellow` was used instead of `below`
- Fixed formatting for the `.env` file tokens section
> BUILD.md typo and formatting fix

- .github/workflows/ci-gitlab.yml
CI is run on PR's and we do not want it running on pushes to main at the moment.
> Don't run gitlab CI on pushes to main

- build/foss/Cargo.lock
- build/foss/Cargo.toml
Update libtelio subdependency trust-dns-server = "0.22.1" to close github dependabot issue: https://github.com/NordSecurity/nordvpn-linux/security/dependabot/19
> Updated rust dependencies

- build/foss/Cargo.lock
In affected of this project, the lifetime of the iterator produced by `Vec::into_iter()` is not constrained to the lifetime of the `Bump` that allocated the vector's memory. Using the iterator after the `Bump` is dropped causes use-after-free accesses.
The following example demonstrates memory corruption arising from a misuse of this unsoundness.
```rb
use bumpalo::{collections::Vec, Bump};
fn main() {
let bump = Bump::new();
let mut vec = Vec::new_in(&bump);
vec.extend([0x01u8; 32]);
let into_iter = vec.into_iter();
drop(bump);
for _ in 0..100 {
let reuse_bump = Bump::new();
let _reuse_alloc = reuse_bump.alloc([0x41u8; 10]);
}
for x in into_iter {
print!("0x{:02x} ", x);
}
println!();
}
```
The issue was corrected by adding a lifetime to the IntoIter type, and updating the signature of …
> Patched Fix bumpalo has use-after-free due to a lifetime error in `Vec::into_iter()`

- cli/cli_groups.go
- cli/messages.go
- daemon/rpc_groups.go
- daemon/rpc_groups_test.go
When groups list is nil, return an error message to let the use know that the list is being fetched.
> Fix daemon crash when groups list is empty

- cli/cli_cities.go
- cli/cli_cities_test.go
When cities list is empty because nothing is cached or failed to fetch it from API, report to the user the message `We couldn’t load the list of cities. Please try again later.`
> Improve error messages for cities command

- cli/cli_mesh_invite.go
- cli/cli_mesh_invite_test.go
When a meshnet peer invite is sent or  accepted, the default option for routing permission is set to OFF. 
`Would you like to allow traffic routing? [y/N]`, `N` will be the default option.
> Set default option for meshnet routing permission to OFF

- cli/cli.go
The device needs to be rebooted after installing nordvpn, otherwise there are problems with `systemd --user`.
Update error message to let the user know that the machine needs to be rebooted instead of just logging out
> Update message that the device needs to be rebooted after install

- config/remote/firebase.go
- config/remote/firebase_test.go
- daemon/vpn/nordlynx/libtelio/libtelio.go
* use cached data as fallback for remote config,when fetching new data fails
* define a default config for telio that also includes direct connections, if fetching fails and there is no cached data
> Use cached data for remote config when fetching fails

- daemon/jobs_test.go
- meshnet/networker.go
- meshnet/server.go
- meshnet/server_test.go
- test/qa/test_meshnet.py
When connecting to a Meshnet peer as an VPN exit, the Meshnet server `s.isPeerConnected` variable was set to `true`. Then this variable was being used during Meshnet disable (`nordvpn set mesh off`) to determine whether we are connected to a Meshnet peer to stop that connection along with Meshnet disable.
However, user can in the meantime connect to a regular VPN server (and thus disconnect from a Meshnet peer). The `s.isPeerConnected` variable was not updated, so Meshnet disabling was resulting in regular VPN disconnect in such case.
The fix is to not use `s.isPeerConnected` variable to remember if we had connected to Meshnet peer, but to check during Meshnet disable the address of currently connected VPN and stop connection only if address indicates that we are connected to a Meshnet …
> Fix VPN disconnected after set meshnet off

- daemon/routes/iprule/iprule.go
- daemon/routes/iprule/iprule_test.go
- test/qa/test_routing.py
When fwmark rule already exists in the system, `r.tableID` is not set to the actual table ID. Instead it stays initialized to `0`, which means that new routes are then added to the `main` table instead of table `205` (or any custom table).
This pull requests changes `checkFwmarkRule` function to `findFwmarkRule`. It will check if fwmark rule already exist and find its table ID. This table ID will be than stored in `r.tableID`.
> Store r.tableID also when fwmark rule is already present

- cmd/daemon/vpn_linux.go
- daemon/connect_test.go
- daemon/jobs_test.go
- daemon/rpc_connect_test.go
- daemon/vpn/nordlynx/kernel_space.go
- daemon/vpn/nordlynx/libtelio/libtelio.go
- daemon/vpn/openvpn/openvpn.go
- daemon/vpn/vpn.go
- meshnet/mesh.go
- networker/networker_test.go
- networker/vpn.go
- networker/vpn_test.go
- test/mock/vpn.go
- test/qa/test_connect.py
- test/qa/test_meshnet.py
For Nordlynx try to reconfigure internally the VPN at network changes, instead of recreating the tunnel.
For OpenVPN is not possible at the moment, because the server config can change between pulls and that internally will trigger the recreation of the tunnel.
> Don't recreate tun at network changes

- core/mesh.go
- meshnet/server.go
A device can send an optional `app_user_uid` field when registering to meshnet. It links the notification center with the meshnet and makes it possible to receive incoming file transfer notifications even if meshnet is disabled. Currently only iOS provide `app_user_uid`, but other platforms started implementing it as well. Therefore, we can remove the iOS check and send the notification to all platforms peers. To not clutter logs with errors in cases when a platform on the other side does not yet support file transfer notifications, suppress 500 Internal Server Error error for that API call.
> Notify all platforms for a new file transfer

- core/mesh/peer.go
In this case nicknames must not be compared with strings.EqualFold. Otherwise if another peer changes the current machine nickname (but only changes the caps), then the current machine will not update its information and will display the older nickname.
> Do not use EqualFold in Machine.IsEqual

- cmd/daemon/events_moose.go
Moose logs will be printed to stdout now. Log level:
* `debug` for development builds
* `error` for production builds
> Add moose logging configuration

- ci/docker/builder/Dockerfile
Enable `go` in `sudo` mode in Builder image. We need to run `cgo` tests in `sudo` mode in Builder image in CI
> Enable go in sudo mode in Builder image

- daemon/vpn/nordlynx/libtelio/libtelio.go
- daemon/vpn/openvpn/openvpn.go
Because the Tun members are interfaces the returned value will always be no-nil, even when the member is nil.
To prevent crashes check in the getter if the member is nil and in that case return nil instead of the member.
> Check for nil inside the Tun function and return nil

- ci/check_dependencies.sh
Replace `--quiet` with `-nv`(no-verbose) to show the errors if wget fails.
> Replace --quiet with -nv for wget

- ipv6/ipv6.go
- kernel/sysctl_setter.go
If IPv6 is disabled from GRUB the application will fail to connect to VPN because it cannot disable IPv6.
> Before disabling IPv6 check if the kernel module is loaded

- kernel/sysctl_setter.go
If error message contains "cannot stat" then the value doesn't exist into the system.
> Correctly check error message from sysctl

- daemon/dns/dns_resolvectl.go
There could be a situation when `systemd` and `resolvectl` get installed in the docker image as a dependency e.g. `openssh-server` but is not active. Out DNS handling methods (one of them) was checking if `resolvectl` command is available in the system and then try to handle DNS settings using that command but it was non-functional. Implemented extra validation.
> Fix dns handling on headless/docker systems

- contrib/changelog/prod/3.17.3_1709544316.md
- contrib/changelog/prod/3.17.4_1712147372.md
- daemon/dns/dns_resolved.go
- internal/filesystem.go
- internal/filesystem_test.go
When LAN access is enabled if the DNS is not correctly configured on the VPN interface will result in DNS leaks.
Fixes: 
* cherry-pick the fix for DNS headless devices
* fix configuring the DNS
> release 3.17.4

- .github/workflows/ci-gitlab.yml
- contrib/changelog/prod/3.17.3_1709544316.md
- fileshare/service/fork.go
- internal/constants.go
- internal/filesystem.go
- internal/filesystem_test.go
Changelog:
* Fixed: Routing through Meshnet devices connected to an OpenVPN server used to mean a trip to no-internet land. Not anymore.
* Fixed: We've refined help-related messages. They're now more accurate, guiding you without the guesswork.
* We’ve made other tweaks and fixes to make your NordVPN experience smoother, faster, and more reliable.
> Release 3.17.3

- .gitignore
- cli/cli_fileshare.go
- cmd/fileshare/main.go
- cmd/norduser/main.go
- fileshare/fileshare_process/fileshare_process_manager.go
- fileshare/filesystem.go
- internal/constants.go
- internal/filesystem.go
- norduser/group_monitor.go
- norduser/grpc_interceptor.go
- norduser/process/norduser_process_manager.go
- norduser/server.go
- norduser/service/combined.go
- norduser/service/fork.go
- norduser/service/snap.go
- snap/snapcraft.yaml
- test/mock/norduser/service/combined.go
Snap sets the value of `$HOME` to `$SNAP_USER_DATA`, therefore explicit
usage of `$SHAN_USER_DATA` is not needed. This results in `$HOME` value
respected in most places with the exception of `addAutostart` as it will
not work if added to `$SNAP_USER_DATA`.
> Fix missing downloads directory in snap package

- tray/monitor.go
- tray/tray.go
* disable notifications by default, and update the value when the tray will be able to fetch the real daemon settings
* `time.Tick` is reported that is leaking. To fix the warning move the time inside `pollingMonitor` and add a defer to stop it, even though for now the function never returns
> Fix tray notifications and remove leak

- tray/menu.go
At meshnet routing some of the fields, like city and country, are empty. In that case remove them from the tray menu.
> Don't show empty fields at meshnet routing

- tray/monitor.go
- tray/notifications.go
- tray/tray.go
Convert notifications status from bool into an enum to be able to differentiate between notifications status from the daemon and that the value is not initialized.
> Use enum for notifications status

- cli/cli_mesh_peers.go
- cli/cli_status.go
- test/qa/lib/meshnet.py
- test/qa/test_meshnet_routing.py
- tray/menu.go
- tray/monitor.go
- tray/tray.go
For tray:
* When the VPN status changes, before displaying notifications, fetch the app settings to have the current notifications settings. Otherwise some notifications might not be displayed.
* Remove the system notification for when the notifications are enabled
* At user logout invalidate account information
* Display notification when connected server changes
* Handle gRPC errors also for other requests, not only for ping
For tray and CLI:
* display VPN server name or meshnet nickname instead of hostname. If they are empty display the hostname
> Change the logic for fetching data from the daemon

- test/qa/lib/notify.py
- test/qa/lib/server.py
- test/qa/test_autoconnect.py
- test/qa/test_connect.py
The app returns server name instead of hostname, update the tests to handle this.
Create a class to store the server info and use it in tests.
> Fix tests because app returns server name instead

- cli/cli_status.go
- test/qa/test_connect.py
- test/qa/test_meshnet_routing.py
For the CLI the `nordvpn status` command will display server name and the hostname when connected to VPN. For meshnet routing will be nickname and hostname. 
Tray will only display the server name for VPN and for Meshnet routing will be peer nickaname if set, otherwise hostname.
> Change how server info is displayed

- snap/snapcraft.yaml.template
Implemented workaround to build packages for multiple architectures - for each target architecture there is a separate snapcraft.yaml.$ARCH (e.g. snapcraft.yaml.arm64) file which gets copied during target architecture build job in CI. 
Submitted request/question to Snapcraft developers forum - to clarify how to use `dump` plugin with multiple target architectures (docs are very abstract) or maybe there is a snapcraft's bug.
> Fix snapcraft to build for multiarch

- cmd/daemon/main.go
- daemon/jobs.go
- Improve Autoconnect report/log that it failed because user is not logged in.
- Improve DNS handling on daemon exit - there was attempt to unset DNS without Network interface which does not make sense and produces error in the log. DNS is being set/unset in Networker with known interface.
> Improve autoconnect

- cli/cli_cities.go
- cli/cli_connect.go
- cli/cli_connect_test.go
- cli/cli_countries.go
- cli/cli_groups.go
- cli/terminal.go
- cli/terminal_test.go
- internal/constants.go
- internal/filesystem.go
* replace `column` command because it is not always available in the system and for snap it cannot be accessed. 
* try to first get the CLI windows size from stdout fd and if it fails try stty
> Remove calls to column command

- core/models.go
- core/models_test.go
- daemon/job_servers.go
- daemon/rpc_connect.go
- daemon/servers.go
- internal/errors.go
* Detect server type from `Specifications` tag. Virtual servers have `virtual_location=true`.
* At connect if virtual servers are not allowed return an error to enable the option if only virtual servers are found.
> Handle virtual servers at VPN connect

- networker/networker.go
- networker/vpn.go
Reset the allowlist at network changes because the OS deletes them when the interface is removed from the system.
> Reset allowlist at network changes

- daemon/helper_test.go
- daemon/job_servers.go
- daemon/rpc_connect.go
- daemon/servers.go
- internal/string.go
- test/qa/lib/settings.py
* Each server has a list of strings computed to faster pick the server when connecting, aka keys. Change functions used to convert the string for keys to be in sync with what is used for user input.
* Keep `string.SnakeCase` function in sync with `string.Title` to remove non-alphanumeric chars from the input.
For testing:
`Lao People's Democratic Republic` contains a `'` in its name. It is displayed `Lao_Peoples_Democratic_Republic ` and connect must work with the displayed name, but also with `Lao_People\'s_Democratic_Republic` so it is backward compatible.
> Change string functions used for servers keys

- request/quic_transport.go
The inner `RoundTripper` can be used by multiple requests in the same time. It can be closed on error or on VPN connection. This 2 operation(execute reques + close) can overlap resulting in a crash because requests are using a closed `RoundTripper`.
To prevent the crash protect access to `RoundTripper` with a `RWLock`. Plus add an `atomic.Bool` to prevent recreating RoundTripper by 2 concurrent requests on the same error.
> Prevent using RoundTripper after it was closed

- daemon/mocks_test.go
- daemon/rpc_set_autoconnect_test.go
- daemon/rpc_set_lan_discovery.go
- daemon/rpc_set_lan_discovery_test.go
- daemon/rpc_set_obfuscate_test.go
- daemon/rpc_set_threat_protection_lite_test.go
* Publish event when LAN discovery changes.
* If LAN discovery is turned on, publish event also that allow lists changed.
> When LAN discovery changes publish the event

- cli/cli.go
- cli/cli_set_autoconnect.go
- cli/cli_set_autoconnect_test.go
- daemon/helper_test.go
- daemon/job_servers_test.go
- daemon/rpc_set_autoconnect.go
- daemon/rpc_set_autoconnect_test.go
* Fix parsing `--group` parameter. `urfave` package doesn't parse flags after the first parameter. In this case for autoconnect would not work because it is specified after `1`, e.g. `nordvpn set autoconnect 1 --group Double_VPN`
* Check the parameter from autoconnect and verify if a server with the specified name can be found. When it doesn't exist and error message is returned.
* Fix unit-tests
> Updates for autoconnect

- test/qa/lib/__init__.py
- test/qa/lib/notify.py
When the application connects to a virtual server it will contain `Virtual` in its connected message, before exclamation point. 
For the moment remove the exclamation point from the message and improve checking when writing tests for virtual servers(there is a separate ticket).
> Remove ! from message checking

- core/mesh.go
- core/mesh_test.go
- core/testdata/mesh_register_200.json
- meshnet/server.go
- meshnet/server_test.go
* Set `Machine.SupportsRouting` otherwise it is false by default and when used can disable the allow routing for current machine
* Always set allow routing to `true` at nickname change, in case config doesn't have the correct value
* Update tests to check if `SupportsRouting` is set to the correct value
> Fix allow routing when changing machine nickname

- auth/auth.go
- auth/auth_test.go
- cli/cli_connect.go
- cli/messages.go
- config/config.go
- config/token.go
- core/models.go
- daemon/jobs_test.go
- daemon/rpc_account.go
- daemon/rpc_connect.go
- daemon/rpc_connect_test.go
- daemon/rpc_set_autoconnect.go
- daemon/rpc_set_autoconnect_test.go
- daemon/servers.go
- internal/codes.go
- meshnet/server_test.go
- protobuf/daemon/account.proto
The list of DIP servers available for a user are part of the DIP service data. At connect and autoconnect use this list instead of calling the servers API.
* Cache the services list for a user to prevent to often API calls [NOT]
* Because the servers list changes in time add a validity duration for DIP service
* If user has DIP subscription but no servers call the API
> Get dedicated IP servers from services data

- build/foss/Cargo.toml
Updates libdrop to 5.5.0-moose-with-context. It fixes issue with missing tracking information
> Update libdrop to 5.5.0-moose-with-context version

- daemon/routes/iprule/iprule.go
- daemon/routes/norule/norule.go
- daemon/routes/rule.go
- internal/string.go
- internal/string_test.go
- networker/networker.go
- networker/networker_test.go
- test/qa/lib/allowlist.py
- test/qa/test_routing.py
Changed allow subnet routing rules to be added as pre-routing and make route decision based on `main` routing table, instead of adding them to table 205 and trying to guess how to route them.
> Improve allowlist routing

- daemon/servers.go
Before using the dedicated IP server, check if it supports the user settings, specially the obfuscation.
> Check if DIP server check supports user settings

- build/foss/Cargo.lock
- magefiles/docker.go
This PR fixes https://github.com/NordSecurity/nordvpn-linux/issues/550
The issue was that when switching a user with `su` the environment gets cleared, including PATH, so `cargo` was not available for the user script switches to
> Fix issue with cleaning environment when switching user

- test/qa/lib/fileshare.py
- test/qa/test_fileshare.py
This PR fixes issue with following scenarios:
- test is sending a file, but the transfer is not accepted and is not cancelled as well
- other test has autoaccept turned on, so the transfer from previous test is accepted, but the working directory of that previous test is already gone (because of test cleanup)
> Fix issue with leftover transfer

- test/qa/test_fileshare.py
This PR fixes the test of nordfileshare process monitoring. `pkill` by default sends `SIGTERM` which is handled by the app and sometimes it happens that the process is finished with cleanup before the assertion starts in the test. Now process will be killed with `SIGKILL` which kills it immediately
> Fix fileshare monitoring test

- snap/snapcraft.yaml
Changes:
- reorder of the architectures to make it consistent
- change of  `- on arm64: ./bin/deps/lib/arm64/` to  `- on arm64: ./bin/deps/lib/aarch64/`
> Fix aarch64 path in snap

- contrib/scriptlets/deb/postinst
- contrib/scriptlets/deb/postrm
Changes:
- call `ldconfig -v` instead of `ldconfig` to properly refresh the linker cache
We found out that calling `ldconfig` alone causes the daemon to fail on first start with error about missing libraries. With second start (when systemd does the restart of the service), it's working properly.
Adding any valid flag to `ldconfig` fixes the issue. Even implementing dummy flag to `ldconfig`, which does nothing, fixes the issue.
> Add verbose flag to ldconfig

- core/core.go
- daemon/job_server_check.go
- daemon/jobs.go
- daemon/jobs_test.go
- daemon/rpc_connect_test.go
- daemon/rpc_login.go
- daemon/rpc_logout.go
- daemon/rpc_logout_test.go
- test/mock/core/core.go
In some cases abstract CombinedAPI were used when some specific functions were needed and they were already available in RPC
> Strip core.CombinedAPI

- cmd/daemon/events_linux.go
- cmd/daemon/main.go
- daemon/events/events.go
- daemon/events/events_test.go
- daemon/job_heartbeat.go
- daemon/jobs.go
- events/moose/moose.go
* HeartBeat events are now sent once meshnet setting updates
* `is_on_vpn` value is always updated after connect and disconnect
> Improve HeartBeat events

- cmd/daemon/main.go
- cmd/norduser/main.go
- fileshare/fileshare_startup/startup.go
GracefulStop will wait for all the current clients to disconnect, otherwise daemon will be stuck there.
Since the daemon will provide a stream for state events, those connections will never close. In this case the daemon will be stuck.
> Use Stop instead of GracefulStop

- cmd/daemon/main.go
- daemon/jobs.go
- events/moose/moose.go
1. Fix invalid arguments to gocron.Scheduler.NewJob
2. Add initial heartbeat checking logic to moose subscriber
> Fix heartbeat events

- ci/check_dependencies.sh
Changes:
- add `--fail-with-body` to fail fast when downloading dependencies
> Add flag to fail fast when downloading .so during build

- ci/docker/tester/requirements.txt
- core/models.go
- core/models_test.go
- daemon/rpc_servers_test.go
- magefiles/mage.go
- test/qa/test_connect.py
- test/qa/test_meshnet_routing.py
* If a server supports one of the obfuscated protocols, TCP or UDP, then it is considered to be obfuscated. Because there can be servers that support only one protocol.
* Increase pytest-timeout to 2.3.1 to fix dependencies errors.
* Use tester image 1.3.2.
> Fix how is checked server obfuscated support

- core/authentication.go
- core/cdn.go
- core/core.go
- core/core_test.go
- core/mesh.go
- daemon/api_repo.go
- pulp/pulp.go
All occurences of `io.ReadAll()` now use `io.LimitReader()` before passing data to the former.
The limit for the reader has been set in [core.go](https://github.com/NordSecurity/nordvpn-linux/blob/a58ca400e7936c264438efa59413dbd455a85481/core/core.go#L24), after discussions the value has been set to `10MB`.
However, it is with some exceptions:
- [daemon/dns/hosts.go](https://github.com/NordSecurity/nordvpn-linux/blob/a58ca400e7936c264438efa59413dbd455a85481/daemon/dns/hosts.go#L88). Reading `/etc/hosts` should not be a subject to any attacks. As editing the file on it's own requires `root` access.
- [events/logger/logger.go NotifyRequestAPIVerbose()](https://github.com/NordSecurity/nordvpn-linux/blob/a58ca400e7936c264438efa59413dbd455a85481/events/logger/logger.go#L58). Marked as "Do not …
> fix: with `io.ReadAll()` use `io.LimitReader()` for DoS prevention

- cmd/fileshare/main.go
- fileshare/event_manager.go
- fileshare/event_manager_test.go
- fileshare/events.go
- fileshare/libdrop/libdrop.go
~~I saw some ideas to implement a channel, but is it actually necessary?~~
~~The implementation of OnEvent() is using a mutex anyways, so no data races should be happening, and Go-routines seem to be light enough to handle this without overusing resources.~~
> feat: non-blocking libdrop event handling

- daemon/jobs_test.go
- meshnet/jobs.go
- meshnet/jobs_test.go
- meshnet/networker.go
- meshnet/server_test.go
- networker/networker.go
- networker/networker_test.go
- test/qa/lib/fileshare.py
- test/qa/test_fileshare.py
Changes:
- no API call for meshnet peers - it uses `MachineMap` now to get peers
- job reacts all the time (not only when it detects process state change) - this prevents the corner case of binding to port early and then enabling meshnet to open the port on firewall
- networker blocks fileshare for all attempts to add the rules (see `netw.isFilesharePermitted`) as long as the process is down
- job runs every second instead of 5s
> Improve fileshare monitoring job

- events/moose/moose_test.go
If the payment status is "error" then consider it invalid.
> Add test for error payment status

- snap/hooks/connect-plug-firewall-control
- snap/hooks/connect-plug-hardware-observe
- snap/hooks/connect-plug-network-control
- snapconf/snapconf.go
Changes:
- new hook for hardware-observe interface to restart the service
- updated the old hooks - looks like ../connections/.. directory is not managed by snap, there are appropriate files in the directory for firewall-control and network-control, but it's not working for other hooks, so this PR changes the method of verifying if the interface is connected
> Fix service restart after adding plug

- ci/docker/tester/Dockerfile
- magefiles/mage.go
- test/qa/lib/__init__.py
Needed for Python tests, as we want to use `dpkg-parsechangelog` tool.
> Add dpkg-dev to tester

- ci/openvpn/check_dependencies.sh
- ci/openvpn/env.sh
The patches for OpenVPN 2.6.12 were removed from master and other tags. The last tag containing the patches is v6.0beta09.
> Set version for tunnelblick patches to version v6.0beta09

- daemon/data_manager.go
- daemon/rpc_servers.go
- daemon/rpc_servers_test.go
* Include Double VPN and Onion over VPN servers into the list.
* To prevent possible race condition on the members of ServersData, when data is changed from DataManager the entire object is replaced instead of only the members.
> Include specialty servers in servers list respose

- daemon/rpc_settings.go
- daemon/rpc_state.go
* Use the same code to convert from config.Settings to pb.Settings for RPC settings and app state event for config change.
* Add PQ status into the notification event information when settings changed.
> Lvpn 7421 include pq status in notifications

- contrib/desktop/nordvpn.desktop
The CLI icon will not be displayed in the system when searching for NordVPN, but still register the mime type.
> LVPN-7402: Hide CLI icon from system apps

- config/manager.go
- daemon/events/events.go
- daemon/state/state.go
Filename and line number of the call to SaveFile will be appended to config update debug log, to make tracing easier in case of log spam.
> LVPN-7510: log caller name for config update

- meshnet/jobs.go
- meshnet/server.go
Job is executed every 1sec, job itself is quick ~1..10ms, but at the `set mesh on` time (or right after it) it's taking longer than 1sec and overlapping with next job run - and gocron scheduler was not configured properly.
> LVPN-7958: Avoid data race in monitorFileshareProcessJob

- ci/docker/snaper/Dockerfile
- magefiles/docker.go
- magefiles/mage.go
- snap/snapcraft.yaml
Changes:
- snaper is now using official snapcraft image from Canonical
- snapcraft needs to run with elevated privileges so after it's done, mage fixes the permissions on the host
- the rest are cosmetic changes - deprecation fixes, formatting etc.
> LVPN-8022: Fix snap build in docker

- events/moose/moose.go
- request/cancellable.go
moose-worker needs to send out all outstanding events before it is stopped. Sometimes this may block the daemon shutdown for longer than necessary. A custom HTTP RoundTripper was added, which allows our moose wrapper to cancel all ongoing HTTP requests on shutdown. This fix was needed primarily for qa tests, as they disconnect/reconnect often, causing issues for the ongoing connections.
> LVPN-7966: Cancellable HTTP context for moose-worker

- meshnet/register.go
- meshnet/register_test.go
There is a delay on the backed between registering a new meshnet/NordLynx key and the key being recognized by the server. It may lead to connection failures, for example when user enables meshnet(registering a new key) and then immediately tries to connect usint NordLynx(key is not recognized yet). A sleep was added to ensure a wait time after new key is registered.
> LVPN-8012: Handle meshnet key registration delay

- fileshare/notification_manager.go
The race occurs because creating a notification for the user and storing this notification ID so that it can be handled later is not handled atomically.
> LVPN-7579: Fix possible data race in NotificationManager

- daemon/vpn/nordlynx/nordlynx.go
- daemon/vpn/nordlynx/nordlynx_test.go
- test/qa/lib/network.py
- test/qa/test_connect.py
* Change netmask for NordLynx to /16 to be able to communicate with the VPN server thru the tunnel.
* Add tests to check that LAN routing works correctly with and without LAN discovery enabled
> LVPN-8094: Change tunnel netmask for NordLynx

- config/server_selection_rules.go
- daemon/rpc_connect.go
- daemon/rpc_connect_test.go
- daemon/servers.go
- events/events.go
- events/moose/moose.go
Changes: 
- Moose events now use **CountryCode** instead of **CountryName** for server connection/disconnection. 
- Implemented **ServerSelectionRule** and **ServerGroup** analytics fields.
> LVPN-7653: Adding additional reporting of server info

- daemon/vpn/nordlynx/libtelio/libtelio.go
- daemon/vpn/nordlynx/libtelio/libtelio_test.go
Change the telio event handling function so that it will block when sending the event downstream when connection is active. Previously, the function would default to dropping the event immediately if receiver was not listening, which would cause some events to be ignored.
> LVPN-8079: Block telio events when event is being handled

- daemon/state/connection_info.go
- daemon/state/connection_info_test.go
- daemon/vpn/events.go
- daemon/vpn/nordlynx/libtelio/libtelio.go
- daemon/vpn/openvpn/openvpn.go
- daemon/vpn/quench/libquench.go
- events/events.go
Changes under this PR:
- Rx/Tx rates are now updated only when status is connected
- removed Rx/Tx rates from events.DataConnect in favour of updating those fields in connection_info, right when providing connection status updated to other clients
- unit test to cover changes
> Provide refreshed transfer rates only when status is connected

- cli/cli_login.go
- config/config.go
Changes:
- CLI reacts to `LoginStatus_CONSENT_MISSING` and triggers consent flow, then continues with login procedure
> LVPN-8136: Execute consent flow in cli on login and register

- cli/cli_click.go
- cli/cli_login.go
- config/config.go
- internal/click_subcommands.go
- internal/click_subcommands_test.go
- internal/errors.go
- tray/actions.go
- tray/notifications.go
Changes:
- `cli_click.go` has new action "consent", this way tray triggers consent flow on login
- this PR enables analytics consent feature by setting `AnalyticsConsent` field to `ConsentUndefined`
- login command in tray triggers the consent by opening `nordvpn://consent` with D-Bus
> LVPN-8137: Execute consent flow in tray

- test/qa/lib/__init__.py
- test/qa/test_meshnet_routing.py
New technology was added to the technologies list used for test parametrization affected the tech ordering so that NordLynx was uset for testing when it shouldn't.
> LVPN-8206: fix route_traffic_to_peer_wrong_tech

- .github/workflows/ci-gitlab.yml
- ci/docker/tester-selenium/requirements.txt
- ci/docker/tester/requirements.txt
- daemon/userconsent.go
- magefiles/mage.go
- test/qa/lib/__init__.py
- test/qa/lib/login.py
- test/qa/lib/settings.py
- test/qa/test_login.py
- test/qa/test_login_nordaccount.py
- test/qa/test_meshnet_other.py
- test/qa/test_settings.py
Changes:
- adds `pexpect` as a dependency to tester and bumps tester image
- updates existing tests to take into account analytics consent
- adds new tests for analytics consent:
- analytics consent displayed on login
- invalid user input repeats the prompt
- ctrl+c causes the prompt to appear again on next login
- after confirming consent it does not appear again
- `nordvpn set analytics` also triggers prompt
- helpers
> LVPN-8307: Update tests for consent

- ci/docker/builder/Dockerfile
- cmd/daemon/main.go
- cmd/daemon/moose_db_creation_test.go
- daemon/data_models.go
- daemon/job_appversion.go
- internal/constants.go
- internal/filesystem.go
- internal/filesystem_test.go
* Allow access to the moose DB only for root and users part of nordvpn group.
* Update FileWrite to always set file permissions, because os.WriteFile is not updating the permissions if the file already exists.
> LVPN-7413: Change moose DB permissions

- test/qa/lib/login.py
- test/qa/test_update.py
Move the login after the application is updated because if the consent was not set then the user will be logged out after app update.
> LVPN 8346: Login after app update

- test/qa/conftest.py
- test/qa/test_allowlist_port.py
- test/qa/test_allowlist_subnet.py
- test/qa/test_autoconnect.py
- test/qa/test_combinations.py
- test/qa/test_connect.py
- test/qa/test_dns.py
- test/qa/test_firewall.py
- test/qa/test_gateway.py
- test/qa/test_grpc.py
- test/qa/test_killswitch.py
- test/qa/test_login.py
- test/qa/test_misc.py
- test/qa/test_notify.py
- test/qa/test_routing.py
There are duplicated setup/teardown functions for daemon start/login in test modules. To get rid of duplicated code, it was  decided to replace it with pytest fixtures.
> LVPN-8118: Replace setup/teardown functions with pytest fixtures

- ci/check_dependencies.sh
Remove the need for GL_ACCESS_TOKEN in CI builds
> Use CI_JOB_TOKEN with internal builds

- test/qa/lib/ssh.py
In case when SSH response is bigger than SSH window_size, reading recv_exit_status before fully reading the response could lead to a deadlock. recv_exit_status would block because no exit status could be received untill full response from the server is read, but client would not accept any more data because the buffer is full. It is a good practice to first read the response, then check for exit status.
> LVPN-8308: fully read SSH response before checking for exit status

- cmd/daemon/events_linux.go
- cmd/daemon/events_moose.go
- cmd/daemon/main.go
- config/build_target.go
- config/machine_id.go
- config/machine_id_test.go
- events/moose/errors.go
- events/moose/moose.go
- magefiles/mage.go
- sysinfo/host_architecture.go
- sysinfo/host_architecture_test.go
Changes:
- Depending on the architecture family, additional information will be provided. For example, ARM CPUs will have additional information on their architecture version (v5, v7, etc.)
- Fixed mage `test:lint` job not printing errors to os.stdout
> LVPN-6013: Integrate Architecture metrics

- cli/cli.go
- cli/cli_cities_test.go
- cli/cli_connect_test.go
- cli/cli_countries_test.go
- cli/cli_groups_test.go
- cli/cli_set_autoconnect_test.go
- cli/cli_test.go
- cli/cli_version.go
- cli/cli_version_test.go
- internal/environment.go
- magefiles/mage.go
- magefiles/scripts.go
- test/helpers/capture_output.go
- test/mock/daemon_client.go
Change the version output to add [snap] at the end of the version when the application is running in snap.
> LVPN-5030: Add snap info into app version output

- test/qa/lib/meshnet.py
[Problem]
Meshnet and Fileshare tests failed with TimeoutError while deleting peers via meshnet functionality during the test setup phase.
[Solution]
Use NordVPN API to explicitly delete all the meshnet peers before the test session run.
- Added 'create_session' function that returns an auth session.
- Added 'get_machine_identifiers' function that fetches the list of machines and returns all 'identifier' values.
- Added 'delete_machines_by_identifier' function that deletes all machines using identifiers
[Test]
meshnet
> LVPN-8573: Cleanup meshnet peers in tests before enabling meshnet

- ci/env.sh
If the version number is not calculated in one line, then executing the env.sh multiple times results in appending the REVISION multiple times, for dev builds.
> Calculate version number in one step

- cmd/daemon/transports.go
- request/h3_reproduce_race_test.go
- request/h3_transport_wrapper.go
- request/h3_transport_wrapper_test.go
This is workaround solution for `quic-go` external library's
issue: https://github.com/quic-go/quic-go/issues/5307
TODO: remove this wrapper when `quic-go` issue is resolved.
> LVPN-8968: Fix http3 data race

- daemon/vpn/mtu.go
- daemon/vpn/mtu_test.go
- daemon/vpn/nordlynx/kernel_space.go
- daemon/vpn/nordlynx/libtelio/libtelio.go
- daemon/vpn/nordlynx/nordlynx.go
- daemon/vpn/nordlynx/nordlynx_test.go
- daemon/vpn/nordlynx/user_space.go
- daemon/vpn/quench/libquench.go
Previously MTU was hardcoded to be 1500, but this would cause issues for singular packets whose size would exceed the actual MTU.
> LVPN-8733: set MTU based on the route's MTU and header size for quench

- gui/rps.yaml
- gui/scripts/build_application.sh
- gui/scripts/build_package.sh
- gui/scripts/generate_protobuf.sh
Changes:
- adjust protobuf generation to use original protobufs instead of submodule
- use migrated docker images available on ghcr.io
> LVPN-8657: Adjust protobuf generation and build

- gui/rps.yaml
- gui/scripts/build_application.sh
- gui/scripts/build_package.sh
Changes:
- don't switch working dir in scripts because running it locally vs in docker is then problematic
- instead, set the proper working dir when running docker
> LVPN-8657: Fix working dir in build scripts

- ci/check_dependencies.sh
- ci/qa_run_tests.sh
- ci/qa_tests_env.sh
- ci/snap/vagrant/Vagrantfile
- ci/snap/vagrant/provision_snap.sh
- ci/snap_functions.sh
- ci/test_snap.sh
- magefiles/vagrant.go
- test/qa/lib/daemon.py
* After the tests are executed save the daemon log into daemon.log
* Add support to use a custom vagrant box for running the tests
* Replace for libvirt sync to nfs to bring the daemon.log to the host
* When running the tests add the current user into the nordvpn group
> LVPN-5404: Save daemon logs when running the tests in snap

- config/static_config.go
- config/static_config_test.go
Issues addressed:
- do not do init twice;
- do not report error if on first start file is not present yet (which is normal case, not error);
> LVPN-8994: Improve static config

- test/qa/lib/__init__.py
This replaces re.match with re.search when checking the connect command output.
* re.match will try to match starting from the beginning of the stdout. 
* re.search will try to find the first match in the entire stdout.
In this way, the test will no longer be affected by additional messages like the one informing the user about a new version available.
> LVPN-9097: Fix tests failing due to the new version available message

- snap/snapcraft.yaml
Changes:
- remove 32 bit architectures from snapcraft.yaml
For CI, there will be a separate PR
> LVPN-9129: Remove 32 bit snap

- test/qa/test_allowlist_port.py
- test/qa/test_allowlist_subnet.py
- test/qa/test_autoconnect.py
- test/qa/test_dns.py
- test/qa/test_fileshare.py
- test/qa/test_login.py
- test/qa/test_meshnet.py
- test/qa/test_meshnet_invite.py
- test/qa/test_meshnet_other.py
- test/qa/test_meshnet_routing.py
- test/qa/test_settings.py
When we are converting `Exception` to `str`, if output is long, it sometimes gets compressed a bit. Once the time comes to compare output to predefined values, the values do not match. As a result, tests fail.
Need to stop converting `Exception` to `str` where possible, and instead use `ex.value.stdout.decode("utf-8")`
> LVPN-8930: Do not convert error messages to string
