ci/docker/tester/requirements.txt
Resolve debendabot issue #12
https://github.com/NordSecurity/nordvpn-linux/security/dependabot/12
=> Resolve debendabot issue #12

daemon/constants.go
=> Fix notification icon

daemon/firewall/allowlist/allowlist_routing.go, daemon/firewall/allowlist/allowlist_routing_test.go, networker/networker.go
=> Remove unneeded allowlist rules

cli/cli_connect_test.go, cli/cli_countries.go, cli/cli_countries_test.go, cli/cli_groups_test.go, daemon/rpc_cities.go, daemon/rpc_cities_test.go, daemon/rpc_countries.go, daemon/rpc_countries_test.go, internal/filesystem.go
* Prevent crashing when countries data is missing.
* Fix test for bash autocomplete for connect
=> Fix crash for countries command

meshnet/register.go, test/qa/test_meshnet.py
=> Fix meshnet not enabling after account switch

daemon/rpc_logout.go
=> Fix logout with NordAccount token not working

ci/data.sh
To generate correct debian change log file, `changelog.yml` file needs to include `deb` section and `packager` must not be empty.
=> Fix changelog yml file

build/foss/Cargo.lock, build/foss/Cargo.toml, ci/download_from_remote.sh, ci/env.sh, cmd/fileshare/main.go, fileshare/drop/drop.go, fileshare/event_manager.go, fileshare/event_manager_test.go, fileshare/fileshare.go, fileshare/filesystem.go, go.mod, go.sum, internal/constants.go
This reverts commit 24a8af73b3b5e46ec36e9400bfb28738d8499224.
=> Revert "Libdrop v5 library update"

cmd/daemon/main.go, config/allowlistlist.go, daemon/events.go, daemon/rpc_set_allowlist.go, daemon/rpc_set_defaults.go, daemon/rpc_set_dns.go, events/events.go, events/logger/settings.go, events/moose/moose.go
Demonstrating logs on daemon startup, dns change, allowlist change (note that allowlist changes weren't logged at all before) and setting defaults:
Before:
```
2023/11/23 15:41:46 [Info] Daemon has started
2023/11/23 15:41:46 Kill Switch set to: disabled
NordVPN App Connection Settings:
Technology: NORDLYNX
Meshnet: disabled
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
ThreatProtectionLite: disabled
DNS:
IPv6: disabled
Notify: disabled
Auto-connect: disabled
2023/11/23 15:41:46 Firewall set to: enabled
NordVPN App Connection Settings:
Technology: NORDLYNX
Meshnet: disabled
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
ThreatProtectionLite: disabled
DNS:
IPv6: disabled
Notify: disabled
Auto-connect: disabled
2023/11/23 15:41:46 Routing …
```
=> Stop logging whole config on every change

ci/docker/packager/Dockerfile, ci/nfpm/build_packages_resources.sh
Rearrange strip in packaging script; Add sudo to packager image
=> Rearrange strip in packaging script; Add sudo to packager image

ci/test_reproducible_builds.sh
Add test if builds are reproducible.
=> Add test if builds are reproducible.

daemon/rpc_connect.go, events/events.go, events/moose/moose.go
Send the correct event duration for connecting to VPN server.
=> Fix connect duration for events

daemon/rpc_connect.go
At connecting the sent data was nil, resulting in wrong message being displayed on the CLI.
=> Send server info to connecting event

cmd/daemon/main.go, internal/chmod_sock.go, internal/constants.go, internal/listener.go, internal/socket.go, internal/socket_test.go
Socket permissions for Snap environment and requesting user authentication
=> Socket permissions for Snap

build/openvpn/build.sh, ci/glibc_version.sh, ci/hardening.sh, ci/nfpm/build_packages_resources.sh, ci/nfpm/template.yaml
It is needed for snap packaging
=> Remove version in openvpn build binary target path

ci/docker/snaper/Dockerfile, snap/snapcraft.yaml
Change snap packaging to use already built binaries
=> Change snap packaging to use already built binaries

contrib/patches/add_moose.diff, go.mod, go.sum
Issue: https://github.com/NordSecurity/nordvpn-linux/security/dependabot/37
=> Fix dependabot issue #37

cmd/daemon/main.go, cmd/fileshare/main.go, cmd/norduser/main.go, fileshare/filesystem.go, norduser/server.go, snapconf/snapconf.go, snapconf/snapconf_test.go
For fileshare in snap try to use $HOME/Downloads as default location for received files
=> In snap Fileshare will try to use user's Downloads

test/qa/lib/network.py, test/qa/test_login_nordaccount.py
When test failure occurs, relevant logging data for troubleshooting issue will be printed.
=> Better logging for NordAccount tests

tray/menu.go, tray/monitor.go, tray/tray.go
* Update tray icon at logout when is connected to VPN
* Try to fetch notifications settings as long as status is invalid, otherwise the no notifications are displayed until the user logs in
=> Update tray icon at logout when is connected to VPN

request/quic_transport.go
When `RoundTripper` is not needed, `Close` function must be called to stop the goroutines.
=> Close HTTP3 round tripper when not needed

auth/auth.go, cli/cli_connect.go, tray/actions.go
=> Fix DIP expiration date in nordvpn account command and subscription

client/messages.go
Add `product_group=nordvpn` param into the subscription URLs 
And `login_target=nordvpn` param for VPN subscription only URL.
=> Update subscription URLs

build/foss/Cargo.lock
Update of dependencies in `Cargo.toml` via `cargo update`.
=> Update rust dependencies

daemon/dns/dns.go, daemon/dns/dns_resolvconf.go, daemon/dns/dns_resolvconf_file.go, daemon/dns/dns_resolvectl.go, daemon/dns/dns_resolved.go, daemon/dns/dns_test.go
Improved DNS handling (canceled the idea to use NetworkManager)
=> Improve DNS handling

test/qa/lib/__init__.py, test/qa/lib/network.py, test/qa/test_combinations.py, test/qa/test_connect.py, test/qa/test_connect6.py, test/qa/test_misc.py
De-duplicate tests, re-use code..
=> Improve connect tests

daemon/vpn/nordlynx/libtelio/config.go, daemon/vpn/nordlynx/libtelio/libtelio.go
Migrate libtelio config up to v4.3.3 (v5.0.0 not yet included)
=> Migrate libtelio config

daemon/firewall/iptables/iptables.go, daemon/firewall/iptables/iptables_test.go, daemon/firewall/rule.go, networker/networker.go, test/qa/lib/firewall.py, test/qa/test_firewall.py
VPN connected gateway will only work when LAN-discovery is ON.    
When LAN-discovery is OFF - during VPN connect, firewall will block INPUT, OUTPUT and FORWARD traffic.
=> Fix forwarding

ci/docker/ruster/Dockerfile, magefiles/mage.go
Fixes build issue with rust version mentioned [here](https://github.com/NordSecurity/nordvpn-linux/issues/550#issuecomment-2281670976)
=> Upgrade rust to 1.80.1 in ruster image

ci/validate_snap.sh, cli/cli_set_technology.go, cli/messages.go
Also one more small change in snap validation script
=> Finalize postquantum texts

daemon/rpc_account.go, daemon/rpc_connect.go, daemon/rpc_disconnect.go, daemon/rpc_login.go
Get/update user's MFA status on:
- login
- connect
- disconnect
- account info
=> Get user MFA status more frequently

events/moose/moose.go
This reason for this change is that there is an issue with reading env vars on the moose side. Moose worker is reading env vars and moose tracker is doing some changes in separate thread leading to invalid pointer access in worker.
The workaround is to reorder the initialization of moose worker and tracker.
=> Start moose worker before the tracker

ci/check_dependencies.sh
Changes:
- check the downloaded library versions before building and break the build if the versions in `lib-versions.env` do not match the downloaded .so files
=> Add libs version check instead building blindly

cmd/daemon/transports_test.go, test/qa/conftest.py, test/qa/lib/firewall.py, test/qa/lib/network.py, test/qa/lib/ssh.py, test/qa/test_connect.py, test/qa/test_fileshare.py
Replace ping where is possible for checking the internet connection.
=> Replace ping for internet checking

cmd/daemon/transports_test.go, test/qa/conftest.py, test/qa/lib/firewall.py, test/qa/lib/network.py, test/qa/lib/ssh.py, test/qa/test_connect.py, test/qa/test_fileshare.py
* add mechanism to stop the running threads when tests are finished
* record traffic with tshart
=> Add tshark at tests monitoring and stop threads

daemon/rpc_connect.go
Changes:
- fixes connection parameters incorrectly set to auto-connect data
=> Fix incorrectly set connection parameters

test/qa/lib/firewall.py
Removing nord dns entries from firewall as they don't impact firewall corectness, only fail tests when the tests check firewall rules before the dns entry happens to be deleted from the firewall.
=> LVPN-7106: Fix allowlist firewall tests

request/quic_transport.go
When `NotifyConnect` is called it used to unnecessarily be locked by other callers during the duration of HTTP call. It is now changed to only read lock for acquiring a reference to the inner `RoundTripper`.
=> LVPN-7433: Fix deadlock in request.QuicTransport

test/qa/lib/fileshare.py, test/qa/test_fileshare.py
* Make code more readable
* Introduce randomness to the size of files that we generate, in order to avoid files with same hash
=> LVPN-6855: Introduce FileSize class in Python tests

daemon/rpc_connect.go
The issue here was that the connection status is being reset on go error, but we have the cases where we are not returning error, but just responding to client with error status code and this case was not handled in defer.
Changes:
- connect function is now returning error and optional payload
- then based on those values I'm resetting the state to "Disconnected"
=> LVPN-7837: Fix wrong connection status

cli/messages.go
Changes:
- use "`" for multiline string and added newlines to improve readability
=> LVPN-8134: Improve consent text in CLI

cli/cli_settings.go, nstrings/bool.go, nstrings/consent_mode.go, nstrings/consent_mode_test.go
Changes:
- `AnalyticsConsent: granted/denied/undefined` changed to `User Consent: enabled/disabled/undefined`
- tests
=> LVPN-8136: Change setting labels

contrib/changelog/prod/4.0.0.md
Changes:
- update release notes for 4.0.0
=> LVPN-8353: Update release 4.0.0 changelog

ci/check_dependencies.sh
Patch to fix unbound variable locally and explanation how to set up local env
=> Add local check_dependencies check

.github/workflows/ci-gitlab.yml, magefiles/mage.go
Detailed info in the Jira ticket
=> Rebuild image to upgrade packages

test/qa/conftest.py, test/qa/lib/log_reader.py, test/qa/lib/remote_config.py, test/qa/lib/remote_config_manager.py, test/qa/test_remote_config.py
- Implemented the initial test automation infrastructure for the RemoteConfig feature.
- Added a few automation tests from the core suite to get things started.
=> LVPN-8129: Prepare core suite of automation tests

ci/qa_run_tests.sh, test/qa/lib/meshnet.py
Tests pattern is optional, when is not set will execute all the tests from the specified categories.
=> LVPN-8995: Make the QA test pattern optional

.github/workflows/ci-gitlab.yml
=> Update triggered-ref to v1.3.1

tray/actions.go, tray/menu.go
=> LVPN-5647: Typo in tray off notifications
